import Link from 'next/link';
import { ArrowRight, ArrowUpRight } from 'lucide-react';
import { Sculpture } from '@/components/portfolio/sculpture';
import { BuildLab } from '@/components/portfolio/build-lab';
import { ScrollGuide } from '@/components/portfolio/scroll-guide';
import { exhibits } from '@/data/exhibits';
export default function Home() {
 return <main id="main"><ScrollGuide/>
  <section className="hero wrap"><div className="hero-copy"><h1>Make it<br/>useful.<em>Then make<br/>it matter.</em></h1><p className="hero-description">Software, intelligent systems,<br/>and the people they serve.</p><a className="hero-cta" href="#lab">Enter the playground <ArrowRight aria-hidden="true"/></a><p className="hero-meta">MSIST · George Washington University<br/>Graduating May 2027</p></div><Sculpture/></section>
  <div className="proof wrap"><div><strong>41</strong><span>students supported</span></div><div><strong>500</strong><span>volunteers mobilized</span></div><p>One question:<br/>what changes for people?</p></div>
  <BuildLab/>
  <section id="work" className="section work wrap"><p className="section-label"><span>02</span> / SELECTED WORK</p><h2>Ideas, <em>out in the world.</em></h2><div className="work-list">{exhibits.map(p=><Link className="work-row" href={`/work/${p.slug}/`} key={p.slug}><span className="work-index mono">{p.index}</span><div className="work-title"><h3>{p.title}</h3><p>{p.line}</p></div><p className="work-summary">{p.summary}</p><div className="work-link"><span>{p.meta}</span><span className="read-link">Read project <ArrowRight size={24}/></span></div></Link>)}</div></section>
  <section id="about" className="section wrap about"><p className="section-label"><span>03</span> / BEYOND THE CODE</p><div className="about-grid"><div><h2>Systems are<br/>made of<br/><em>people,</em> too.</h2><p className="about-copy">From teaching Python at GW to leading community initiatives in India, I care about what technology makes possible for people.</p></div><div className="impact"><div><strong>41</strong><p>students supported<br/>at GW</p></div><div><strong>500</strong><p>volunteers mobilized<br/>with NSS</p></div><div><strong>120+</strong><p>community<br/>initiatives</p></div><p className="source-note">Figures from my résumé.</p></div></div><details className="experience"><summary>Experience & the longer story <PlusIcon/></summary><div className="experience-rows"><article><time>2026 — PRESENT</time><h3>Graduate Instructional Assistant</h3><p>George Washington University. Python setup, debugging support, course administration, and laboratory instruction across two courses.</p></article><article><time>JAN — JUN 2024</time><h3>Digital Marketing Intern</h3><p>AKS Clinic. Coordinated AI video campaigns, content delivery, stakeholder approvals, and weekly performance reporting.</p></article><article><time>MAY — JUL 2023</time><h3>Machine Learning Intern</h3><p>Tech Simba. Supported an AI résumé-screening tool through requirements, evaluation documentation, data pipelines, and performance dashboards.</p></article><article><time>AUG 2022 — DEC 2023</time><h3>Vice President, National Service Scheme</h3><p>Bennett University. Led a 30-member executive team and coordinated volunteers, partners, logistics, and community programs.</p></article></div><p className="personal-note">BCA, Artificial Intelligence · Bennett University, 2024.<br/>Off-screen: basketball, astronomy, and philosophy.</p></details></section>
  <section id="contact" className="contact wrap"><h2>Let’s build something<br/><em>worth using.</em></h2><div className="contact-links"><a className="email" href="mailto:kunalm@gwu.edu">kunalm@gwu.edu</a><a href="https://github.com/kunal2003" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={21}/></a><a href="mailto:kunalm@gwu.edu?subject=Resume%20request">Request résumé <ArrowUpRight size={21}/></a></div></section>
 </main>;
}
function PlusIcon(){return <span aria-hidden="true">+</span>}
